### ISSUE TITLE
パスキー包括的テスト実装

### ISSUE THREAD

**Issue by tetran** [tetran/Hotwire-ToDo#144]
## 概要
パスキー認証システムの信頼性を保証するため、包括的なテストスイートを実装する。ユニット・統合・システム・E2Eテストを含む。

関連: #5 （パスキー認証実装）
依存: #143 （パスキーアクセシビリティ・国際化対応）

## 受け入れ基準
- [ ] 全機能のユニットテスト実装（90%以上カバレッジ）
- [ ] 統合テストの完全実装
- [ ] E2Eテストシナリオ実装
- [ ] パフォーマンステスト実装
- [ ] セキュリティテスト実装

### 1. ユニットテスト
```ruby
# test/models/webauthn_credential_test.rb
class WebauthnCredentialTest < ActiveSupport::TestCase
  test "should validate external_id uniqueness per user and provider" do
    # 重複検証テスト
  end
  
  test "should update last_used_at on touch" do
    # 使用記録テスト
  end
  
  test "should generate appropriate display_name" do
    # 表示名生成テスト
  end
end
```

### 2. コントローラーテスト
```ruby
# test/controllers/webauthn/registrations_controller_test.rb
class Webauthn::RegistrationsControllerTest < ActionDispatch::IntegrationTest
  test "should generate registration options" do
    # 登録オプション生成テスト
  end
  
  test "should verify and save credential" do
    # 認証情報検証・保存テスト
  end
  
  test "should handle registration errors gracefully" do
    # エラーハンドリングテスト
  end
end
```

### 3. システムテスト
```ruby
# test/system/passkey_authentication_test.rb
class PasskeyAuthenticationTest < ApplicationSystemTestCase
  test "user can register passkey successfully" do
    # パスキー登録フローテスト
  end
  
  test "user can authenticate with passkey" do
    # パスキー認証フローテスト
  end
  
  test "user can manage multiple passkeys" do
    # 複数パスキー管理テスト
  end
end
```

### モデルテスト
- [ ] **WebauthnCredential**: バリデーション・メソッド・スコープ
- [ ] **User**: パスキー関連メソッド・関連付け
- [ ] **WebauthnAuditLog**: ログ記録・検索機能

### コントローラーテスト
- [ ] **RegistrationsController**: 登録フロー・エラー処理
- [ ] **AuthenticationsController**: 認証フロー・セッション管理
- [ ] **PasskeySettingsController**: 管理機能・操作権限

### サービステスト
- [ ] **PasskeySecurityService**: セキュリティ機能・異常検知
- [ ] **WebauthnProviderDetector**: プロバイダー検出精度

### 統合テスト
- [ ] **認証フロー統合**: パスワード・TOTP・パスキー連携
- [ ] **API統合**: WebAuthn API呼び出し・レスポンス処理
- [ ] **セッション統合**: 認証状態管理・継続性

### E2Eテスト
```ruby
# test/system/passkey_complete_flow_test.rb
test "complete passkey lifecycle" do
  # 1. ユーザー登録
  # 2. パスキー登録
  # 3. パスキー認証
  # 4. 設定変更
  # 5. パスキー削除
end
```

### WebAuthn API モック
```javascript
// test/javascript/webauthn_mock.js
class WebAuthnMock {
  static mockCreate(options) {
    return Promise.resolve({
      id: 'mock_credential_id',
      rawId: new ArrayBuffer(32),
      response: {
        clientDataJSON: 'mock_client_data',
        attestationObject: 'mock_attestation'
      }
    });
  }
  
  static mockGet(options) {
    return Promise.resolve({
      id: 'mock_credential_id',
      response: {
        authenticatorData: 'mock_auth_data',
        signature: 'mock_signature'
      }
    });
  }
}
```

### セキュリティテスト
- [ ] **CSRF攻撃**: トークン検証テスト
- [ ] **リプレイ攻撃**: チャレンジ一意性テスト
- [ ] **権限昇格**: 認可チェックテスト
- [ ] **データ漏洩**: 機密データ保護テスト

### パフォーマンステスト
```ruby
# test/performance/passkey_performance_test.rb
class PasskeyPerformanceTest < ActionDispatch::IntegrationTest
  test "authentication response time under load" do
    # 認証処理のレスポンス時間測定
  end
  
  test "registration handles concurrent requests" do
    # 並行登録処理テスト
  end
end
```

### フィクスチャ設計
```yaml
# test/fixtures/webauthn_credentials.yml
alice_passkey:
  user: alice
  external_id: "alice_passkey_id_123"
  public_key: <%= Base64.encode64("mock_public_key") %>
  nickname: "Alice's iPhone"
  provider: "safari"
  sign_count: 5
  last_used_at: <%= 1.hour.ago %>

bob_passkey:
  user: bob
  external_id: "bob_passkey_id_456"
  public_key: <%= Base64.encode64("mock_public_key_2") %>
  nickname: "Bob's Chrome"
  provider: "chrome"
  sign_count: 12
  last_used_at: <%= 1.day.ago %>
```

### 基盤テスト
- [ ] テストヘルパー・ユーティリティ作成
- [ ] WebAuthn APIモック実装
- [ ] フィクスチャデータ作成
- [ ] テスト設定・環境構築

### 機能テスト実装
- [ ] モデルテスト完全実装
- [ ] コントローラーテスト実装
- [ ] サービステスト実装
- [ ] 統合テスト実装
- [ ] システムテスト実装

### 特殊テスト
- [ ] セキュリティテスト実装
- [ ] パフォーマンステスト実装
- [ ] エラーケーステスト実装
- [ ] 境界値テスト実装

### テストツール・CI/CD統合
- [ ] カバレッジ測定設定
- [ ] 継続的テスト実行設定
- [ ] テストレポート生成
- [ ] 失敗時通知設定

## 品質目標
- [ ] **コードカバレッジ**: 90%以上
- [ ] **テスト実行時間**: 5分以内
- [ ] **テスト成功率**: 99%以上
- [ ] **セキュリティテスト**: 全項目合格

## 見積もり
**3日**（24時間程度）

## 注意点
- WebAuthn APIの非同期性への対応
- ブラウザ環境依存テストの分離
- CI/CD環境でのHeadlessブラウザ設定
- テストデータの適切な管理・クリーンアップ
